POST http://localhost:3001/api/exercises
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVwcHUiLCJpZCI6MiwiaWF0IjoxNjQ3NTkyNTExLCJleHAiOjE2NDc1OTYxMTF9.U_WutAcPQP2KIZfyHpzzluKfjFhz8RnNZmfo3lYqHsc

{
  "sport": "Skiing",
  "start_time": "2022-03-17 17:50",
  "duration": "01:00",
  "distance": "10.5",
  "avg_hr": "130"
}