POST http://localhost:3001/api/exercises
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVwcHUiLCJpZCI6MSwiaWF0IjoxNjQ3NTE2NTAzLCJleHAiOjE2NDc1MjAxMDN9.EsC_ypZrw-yWpHaT0JP82XhucpyfZc0MlS1UTq2-Kds

{
  "sport": "Skiing",
  "start_time": "2022-03-17 17:50",
  "duration": "01:00",
  "distance": "10.5",
  "avg_hr": "130"
}